# Generated by Django 3.0.5 on 2020-06-22 14:02

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('possible_unit', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('dish_types', models.CharField(blank=True, max_length=1024, null=True)),
                ('servings', models.IntegerField()),
                ('readyInMinutes', models.IntegerField()),
                ('summary', models.TextField()),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
                ('inductions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=1024, null=True)),
                ('ingredients_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecipesManager.Ingredients')),
                ('recipes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipesManager.Recipes')),
            ],
        ),
    ]
