# Generated by Django 3.0.5 on 2020-06-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesManager', '0002_auto_20200625_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='ingredients_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recipe_ingredients',
            old_name='recipes_id',
            new_name='recipe',
        ),
    ]
