# Generated by Django 3.0.5 on 2020-06-24 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesManager', '0003_auto_20200625_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RecipesManager.Ingredients', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='recipe_ingredients',
            unique_together={('recipe', 'ingredient')},
        ),
    ]
