# Generated by Django 3.0.5 on 2020-07-04 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesManager', '0005_auto_20200625_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient', to='RecipesManager.Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='RecipesManager.Recipes'),
        ),
    ]
