# Generated by Django 3.0.5 on 2020-07-17 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
        ('RecipesManager', '0006_auto_20200704_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author', to='usermanager.Users'),
        ),
    ]
