# Generated by Django 3.0.5 on 2020-07-17 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
        ('RecipesManager', '0007_recipes_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='usermanager.Users'),
        ),
    ]
