# Generated by Django 3.0.5 on 2020-06-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1024, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('full_name', models.CharField(max_length=512)),
                ('display_name', models.CharField(max_length=512, null=True)),
                ('gender', models.CharField(default='Male', max_length=20, null=True)),
                ('birthday', models.DateField(default='1-1-1990')),
                ('avatar', models.URLField(null=True)),
            ],
        ),
    ]
